using System;

namespace WoWDaemon.Common
{
	public enum CMSG : int
	{
		CHAR_CREATE = 0x0036,
		CHAR_DELETE = 0x0038,
		CHAR_ENUM = 0x37,
		PLAYER_LOGIN = 0x3D,
		LOGOUT_REQUEST = 0x4B,
		NAME_QUERY = 0x50,
		ITEM_QUERY_SINGLE = 0x56,
		CREATURE_QUERY = 0x60,

		MESSAGECHAT = 0x95,

		MOVE_START_FORWARD = 0x00B5,
		MOVE_START_BACKWARD = 0x00B6,
		MOVE_STOP = 0x00B7,
		MOVE_START_STRAFE_LEFT = 0x00B8,
		MOVE_START_STRAFE_RIGHT = 0x00B9,
		MOVE_STOP_STRAFE = 0x00BA,
		MOVE_JUMP = 0x00BB,
		MOVE_START_TURN_LEFT = 0x00BC,
		MOVE_START_TURN_RIGHT = 0x00BD,
		MOVE_STOP_TURN = 0x00BE,
		MOVE_START_PITCH_UP = 0x00BF,
		MOVE_START_PITCH_DOWN = 0x00C0,
		MOVE_STOP_PITCH = 0x00C1,
		MOVE_SET_RUN_MODE = 0x00C2,
		MOVE_SET_WALK_MODE = 0x00C3,
		MOVE_COLLIDE_REDIRECT = 0x00C9,
		MOVE_COLLIDE_STUCK = 0x00CA,
		MOVE_START_SWIM = 0x00CB,
		MOVE_STOP_SWIM = 0x00CC,

		MOVE_SET_RUN_SPEED_CHEAT = 0x00CD,
		MOVE_SET_RUN_SPEED = 0x00CE,
		MOVE_SET_WALK_SPEED_CHEAT = 0x00CF,
		MOVE_SET_WALK_SPEED = 0x00D0,
		MOVE_SET_SWIM_SPEED_CHEAT = 0x00D1,
		MOVE_SET_SWIM_SPEED = 0x00D2,
		MOVE_SET_ALL_SPEED_CHEAT = 0x00D3,
		MOVE_SET_TURN_RATE_CHEAT = 0x00D4,
		MOVE_SET_TURN_RATE = 0x00D5,

		MOVE_SET_FACING = 0x00D7,
		MOVE_SET_PITCH = 0x00D8,
		MOVE_WORLDPORT_ACK = 0x00D9,
		MOVE_HEARTBEAT = 0x00E9,
		// spells
        NEW_SPELL_SLOT = 0x0120,
		CAST_SPELL = 0x0121,
		CANCEL_CAST = 0x0122,
        CANCEL_AURA = 0x0129,
        //who list
		WHO = 0x0062,
		WHOIS = 0x0064,
		RWHOIS  = 0x01EE,

		STANDSTATECHANGED = 0xF4,
		EMOTE = 0x00F5,
		TEXT_EMOTE = 0x00F7,
		PING  = 0x01CD,
		AUTH_SESSION  = 0x01DE,
		REQUEST_UI_CONFIG = 0x1FB,
		SAVE_UI_CONFIG = 0x01FC,
		MAX,
	}

	public enum SMSG : int
	{
		CHAR_CREATE = 0x003A,
		CHAR_DELETE = 0x003C,
		CHAR_ENUM = 0x3B,
		NEW_WORLD = 0x3E,
		LOGOUT_COMPLETE = 0x4D,

		NAME_QUERY_RESPONSE = 0x51,
		ITEM_QUERY_SINGLE_RESPONSE = 0x58,
		CREATURE_QUERY_RESPONSE = 0x61,

		MESSAGECHAT = 0x96,
		
		OBJECT_UPDATE = 0xA9,
		OBJECT_DESTROY = 0xAA,

		MOVE_START_FORWARD = 0x00B5,
		MOVE_START_BACKWARD = 0x00B6,
		MOVE_STOP = 0x00B7,
		MOVE_START_STRAFE_LEFT = 0x00B8,
		MOVE_START_STRAFE_RIGHT = 0x00B9,
		MOVE_STOP_STRAFE = 0x00BA,
		MOVE_JUMP = 0x00BB,
		MOVE_START_TURN_LEFT = 0x00BC,
		MOVE_START_TURN_RIGHT = 0x00BD,
		MOVE_STOP_TURN = 0x00BE,
		MOVE_START_PITCH_UP = 0x00BF,
		MOVE_START_PITCH_DOWN = 0x00C0,
		MOVE_STOP_PITCH = 0x00C1,
		MOVE_SET_RUN_MODE = 0x00C2,
		MOVE_SET_WALK_MODE = 0x00C3,
		MOVE_COLLIDE_REDIRECT = 0x00C9,
		MOVE_COLLIDE_STUCK = 0x00CA,
		MOVE_START_SWIM = 0x00CB,
		MOVE_STOP_SWIM = 0x00CC,

		MOVE_SET_RUN_SPEED_CHEAT = 0x00CD,
		MOVE_SET_RUN_SPEED = 0x00CE,
		MOVE_SET_WALK_SPEED_CHEAT = 0x00CF,
		MOVE_SET_WALK_SPEED = 0x00D0,
		MOVE_SET_SWIM_SPEED_CHEAT = 0x00D1,
		MOVE_SET_SWIM_SPEED = 0x00D2,
		MOVE_SET_ALL_SPEED_CHEAT = 0x00D3,
		MOVE_SET_TURN_RATE_CHEAT = 0x00D4,
		MOVE_SET_TURN_RATE = 0x00D5,
		

		MOVE_SET_FACING = 0x00D7,
		MOVE_SET_PITCH = 0x00D8,
		MONSTER_MOVE = 0x00DA,
		FORCE_SPEED_CHANGE = 0x00DF,
		MOVE_HEARTBEAT = 0x00E9,
		//spells
		INITIAL_SPELLS = 0x011D,
		LEARNED_SPELL = 0x011E,
		SUPERCEDED_SPELL = 0x011F,
		CAST_RESULT = 0x0123,
		SPELL_START = 0x0124,
		SPELL_GO = 0x0125,
		SPELL_FAILURE = 0x0126,
		SPELL_COOLDOWN = 0x0127,
		COOLDOWN_EVENT = 0x0128,
        UPDATE_AURA_DURATION = 0x012A,
        PET_CAST_FAILED = 0x012B,
		SPELLNONMELEEDAMAGELOG = 0x024E, //test from 0.8 beta
        //who list
		WHO = 0x0063,
		WHOIS = 0x0065,
        RWHOIS  = 0x01EF,

		TUTORIAL_FLAGS = 0x00F0,
		EMOTE = 0x00F6,
		TEXT_EMOTE = 0x00F8,
		ACTION_BUTTONS = 0x011C,
		PONG  = 0x01CE,
		AUTH_CHALLENGE  = 0x01DD,
		AUTH_RESPONSE  = 0x01DF,
		COMPRESSED_UPDATE_OBJECT  = 0x01E7,
		UI_CONFIG_MD5 = 0x1FA,
		UI_CONFIG = 0x1FD,
		MAX,
	}

	public enum WORLDMSG : int
	{
		INIT_WORLD, // only from loginserver
		WORLD_SHUTDOWN,
		INIT_MAPS,
		CHANGE_MAP,
		ADD_MAP, // for future use
		REMOVE_MAP, // for future use
		CREATE_DBOBJECT,
		CREATE_DBOBJECT_REPLY,
		DELETE_DBOBJECT,
		DESERIALIZE_OBJ, // maybe sent from both
		PLAYER_ENTER_WORLD, // only from loginserver
		PLAYER_LEAVE_WORLD, // could be sent from both
		CLIENT_MESSAGE, // CMSG
		SERVER_MESSAGE, // SMSG
		INIT_GUIDS, // from login server
		ACQUIRE_GUIDS, // only from a worldserver
		ACQUIRE_GUIDS_REPLY, // only from loginserver
		SCRIPT_MESSAGE,
		INIT_SPELLS,
		MAX,
	}


	#region enum RESTEDSTATE
	public enum RESTEDSTATE : byte
	{
		WELLRESTED = 1,
		RESTED,
		NORMAL,
		TIRED,
		EXHAUSTED
	}
	#endregion

	#region enum CHATMESSAGETYPE
	public enum CHATMESSAGETYPE : int
	{
		SAY,
		PARTY,
		GUILD,
		OFFICER,
		YELL,
		WHISPER,
		WHISPER_INFORM,
		EMOTE,
		TEXT_EMOTE,
		SYSTEM,
		MONSTER_SAY,
		MONSTER_YELL,
		MONSTER_EMOTE,
		CHANNEL,
		CHANNEL_JOIN,
		CHANNEL_LEAVE,
		CHANNEL_LIST,
		CHANNEL_NOTICE,
		CHANNEL_NOTICE_USER,
		AFK,
		DND,
		COMBAT_LOG,
		IGNORED,
		SKILL,
		LOOT,
		COMBAT_LOG_ENEMY,
		COMBAT_LOG_SELF,
		COMBAT_LOG_PARTY,
		COMBAT_LOG_ERROR,
		COMBAT_LOG_MISC_INFO,
		MAX
	};
	#endregion

	#region enum INVSLOT
	public enum INVSLOT : byte
	{
		EQUIPPEDFIRST = 0,
		HEAD = 0,
		NECK,
		SHOULDER,
		BODY,
		CHEST,
		WAIST,
		LEGS,
		FEET,
		WRIST,
		HAND,
		FINGER1,
		FINGER2,
		TRINKET1,
		TRINKET2,
		BACK,
		MAINHAND,
		OFFHAND,
		RANGED,
		TABARD = 0x12,
		EQUIPPEDLAST = 0x12,
		NONE_EQUIPFIRST = 0x13,
		BAG0 = 0x13,
		BAGFIRST = 0x13,
		BAG1 = 0x14,
		BAG2 = 0x15,
		BAG3 = 0x16,
		BAGLAST = 0x16,
		BACKPACK_START = 0x17,
		BACKPACK_SLOT00 = 0x17,
		BACKPACK_FIRST = 0x17,
		BACKPACK_SLOT01 = 0x18,
		BACKPACK_SLOT02 = 0x19,
		BACKPACK_SLOT03 = 0x1A,
		BACKPACK_SLOT04 = 0x1B,
		BACKPACK_SLOT05 = 0x1C,
		BACKPACK_SLOT06 = 0x1D,
		BACKPACK_SLOT07 = 0x1E,
		BACKPACK_SLOT08 = 0x1F,
		BACKPACK_SLOT09 = 0x20,
		BACKPACK_SLOT10 = 0x21,
		BACKPACK_SLOT11 = 0x22,
		BACKPACK_SLOT12 = 0x23,
		BACKPACK_SLOT13 = 0x24,
		BACKPACK_SLOT14 = 0x25,
		BACKPACK_SLOT15 = 0x26,
		BACKPACK_LAST = 0x26,
		BANKGENERIC_SLOT00 = 0x27,
		BANKGENERIC_FIRST = 0x27,
		BANKGENERIC_SLOT01 = 0x28,
		BANKGENERIC_SLOT02 = 0x29,
		BANKGENERIC_SLOT03 = 0x2A,
		BANKGENERIC_SLOT04 = 0x2B,
		BANKGENERIC_SLOT05 = 0x2C,
		BANKGENERIC_SLOT06 = 0x2D,
		BANKGENERIC_SLOT07 = 0x2E,
		BANKGENERIC_SLOT08 = 0x2F,
		BANKGENERIC_SLOT09 = 0x30,
		BANKGENERIC_SLOT10 = 0x31,
		BANKGENERIC_SLOT11 = 0x32,
		BANKGENERIC_SLOT12 = 0x33,
		BANKGENERIC_SLOT13 = 0x34,
		BANKGENERIC_SLOT14 = 0x35,
		BANKGENERIC_SLOT15 = 0x36,
		BANKGENERIC_SLOT16 = 0x37,
		BANKGENERIC_SLOT17 = 0x38,
		BANKGENERIC_SLOT18 = 0x39,
		BANKGENERIC_SLOT19 = 0x3A,
		BANKGENERIC_SLOT20 = 0x3B,
		BANKGENERIC_SLOT21 = 0x3C,
		BANKGENERIC_SLOT22 = 0x3D,
		BANKGENERIC_SLOT23 = 0x3E,
		BANKGENERIC_LAST = 0x3E,
		BANKBAG_FIRST = 0x3F,
		BANKBAG_LAST = 0x44,
		MAX = 0x45,
		PLAYER_INVENTORY_SLOTS  =0x45,
		NUM_INVENTORY_SLOTS =0x17,
		NUM_BAG_SLOTS  = 0x4,
		MIN_BACKPACK_SLOTS =0x10,
		BANK_NUM_GEMERIC_SLOTS =0x18,
		NUM_BANKBAG_SLOTS = 0x6,
		TOTAL_BAG_SLOTS = 0xA,
	}
	#endregion

	#region enum ITEMCLASS
	public enum ITEMCLASS
	{
		CONSUMABLE = 0x00,
		CONTAINER = 0x01,
		WEAPON = 0x02,
		NOTVALID3 = 0x03, // JEWELRY OBSOLETE?
		ARMOUR = 0x04,
		REGEANT = 0x05,
		PROJECTILE = 0x06, // MAYBE
		TRADEGOODS = 0x07,
		NOTVALID8 = 0x08, // GENERIC OBSOLETE?
		BOOK = 0x09,
		MONEY = 0x0A,
		QUIVER = 0x0B,
		QUEST = 0x0C,
		KEYLOCKPICK = 0x0D,
		PERMANENT = 0x0E,
		JUNK = 0x0F,
		MAX
	}
	#endregion

	#region enum WEAPONSUBCLASS
	public enum WEAPONSUBCLASS
	{
		ONEHANDAXE = 0,
		TWOHANDAXE = 1,
		BOW = 2,
		GUN = 3,
		ONEHANDBLUNT = 4,
		TWOHANDBLUNT = 5,
		POLEARM = 6,
		ONEHANDSWORD = 7,
		TWOHANDSWORD = 8,
		NOTVALID9,
		STAFF = 10,
		ONEHANDEXOTIC = 11,
		TWOHANDEXOTIC = 12,
		UNARMED = 13,
		GENERIC = 14,
		DAGGER = 15,
		THROWN = 16,
		SPEAR = 17,
		CROSSBOW = 18,
		WAND = 19,
	}
	#endregion

	#region enum ARMOURSUBCLASS
	public enum ARMOURSUBCLASS
	{
		GENERIC,
		CLOTH,
		LEATHER,
		MAIL,
		PLATE,
		BUCKLER,
		SHIELD
	}
	#endregion

	#region enum QUIVERSUBCLASS
	public enum QUIVERSUBCLASS
	{
		OBSOLETE_QUIVER,
		BOLT_QUIVER,
		ARROW_QUIVER,
		AMMO_POUCH,
	}
	#endregion

	#region enum PROJECTILESUBCLASS
	public enum PROJECTILESUBCLASS
	{
		WAND,
		BOLT,
		ARROW,
		BULLET,
		THROWN,
	}
	#endregion

	#region enum INVTYPE
	public enum INVTYPE
	{
		NONE_EQUIP = 0x00,
		HEAD = 0x01,
		NECK = 0x02,
		SHOULDER = 0x03,
		BODY = 0x04,
		CHEST = 0x05,
		WAIST = 0x06,
		LEGS = 0x07,
		FEET = 0x08,
		WRIST = 0x09,
		HAND = 0x0A,
		FINGER = 0x0B,
		TRINKET = 0x0C,
		WEAPON = 0x0D,
		SHIELD = 0x0E,
		RANGED = 0x0F,
		CLOAK = 0x10,
		TWOHANDEDWEAPON = 0x11,
		BAG = 0x12,
		TABARD = 0x13,
		ROBE = 0x14,
		WEAPONMAINHAND = 0x15,
		WEAPONOFFHAND = 0x16,
		HOLDABLE = 0x17,
		AMMO = 0x18,
		THROWN = 0x19,
		RANGEDRIGHT = 0x1A,
		NUM_TYPES = 0x1B
	}
	#endregion

	#region enum OBJECTTYPE
	public enum OBJECTTYPE
	{
		OBJECT,
		ITEM,
		CONTAINER,
		UNIT,
		PLAYER,
		GAMEOBJECT,
		DYNAMICOBJECT,
		CORPSEOBJECT,
		MAX
	}
	#endregion

	#region enum HIER_OBJECTTYPE
	public enum HIER_OBJECTTYPE : int
	{
		OBJECT = 0x1,
		ITEM = 0x3,
		CONTAINER = 0x07,
		UNIT = 0x9,
		PLAYER = 0x19,
		GAMEOBJECT = 0x21,
		DYNAMICOBJECT = 0x41,
		CORPSEOBJECT = 0x81
	}
	#endregion

	#region enum OBJECTFIELDS
	public enum OBJECTFIELDS
	{
		GUID = 0,
		HIER_TYPE = 2,
		ENTRY = 3,
		SCALE = 4,
		PADDIND = 5,
		MAX = 6,
	}
	#endregion

	#region enum ITEMFIELDS
	public enum ITEMFIELDS
	{
		OWNER = 6,
		CONTAINED = 8,
		CREATOR = 10,
		STACK_COUNT = 12,
		DURATION = 13,
		SPELL_CHARGES = 14,
		FLAGS = 19,
		ENCHANTMENTS = 20,
		PROPERTY_SEED = 41,
		RANDOM_PROPERTIES_ID = 42,
		PADDING = 43,
		MAX = 44,
	}
	#endregion

	#region enum CONTAINERFIELDS
	public enum CONTAINERFIELDS
	{
		NUM_SLOTS = 44,
		ALIGN_PAD = 45,
		SLOTS = 46,
		MAX = 86,
	}
	#endregion

	#region enum UNITFIELDS
	public enum UNITFIELDS
	{
		CHARMED = 6,
		SUMMON = 8,
		CHARMEDBY = 10,
		SUMMONEDBY = 12,
		CREATEDBY = 14,
		TARGET = 16,
		COMBO_TARGET = 18,
		CHANNEL_OBJECT = 20,
		HEALTH = 22,
		POWER0 = 23,
		MANA = 23,
		RAGE = 24,
		FOCUS = 25,
		ENERGY = 26,
		MAX_HEALTH = 27,
		MAX_POWER0 = 28,
		MAX_MANA = 28,
		MAX_RAGE = 29,
		MAX_FOCUS = 30,
		MAX_ENERGY = 31,
		LEVEL = 32,
		FACTION = 33,
		BYTES_0 = 34,
		STATS0 = 35,
		STRENGTH = 35,
		AGILITY = 36,
		STAMINA = 37,
		INTELLECT = 38,
		SPIRIT = 39,
		BASE_STATS0 = 40,
		BASE_STRENGTH = 40,
		BASE_AGILITY = 41,
		BASE_STAMINA = 42,
		BASE_INTELLECT = 43,
		BASE_SPIRIT = 44,
		VIRTUAL_ITEMSLOTDISPLAY = 45,
		VIRTUAL_ITEMINFO = 48,
		FLAGS = 54,
		COINAGE = 55,
		AURA = 56,
		AURA_LEVELS = 112,
		AURA_APPLICATIONS = 122,
		AURA_FLAGS = 132,
		AURA_STATE = 139,
		BASEATTACKTIME0 = 140,
		BASEATTACKTIME1 = 141,
		RESISTANCE = 142,
		RESIST_PHYSICAL = 142,
		RESIST_HOLY = 143,
		RESIST_FIRE = 144,
		RESIST_NATURE = 145,
		RESIST_FROST = 146,
		RESIST_SHADOW = 147,
		BOUNDING_RADIUS = 148,
		COMBAT_REACH = 149,
		WEAPON_REACH = 150,
		DISPLAYID = 151,
		MOUNT_DISPLAYID = 152,
		MIN_DAMAGE = 153,
		MAX_DAMAGE = 154,
		MOD_DAMAGE_DONE = 155,
		RESISTANCE_BUFF_POSITIVE = 161,
		RESISTANCE_BUFF_NEGATIVE = 167,
		RESISTANCE_ITEM_MODS = 173,
		BYTES_1 = 179,
		PET_NUMBER = 180,
		PET_NAME_TIMESTAMP = 181,
		PET_EXPERIENCE = 182,
		PET_NEXT_LEVE_EXP = 183,
		DYNAMIC_FLAGS = 184,
		EMOTE_STATE = 185,
		CHANNEL_SPELL = 186,
		MOD_CAST_SPEED = 187,
		CREATED_BY_SPELL = 188,
		NPC_FLAGS = 189,
		BYTES_2 = 190,
		ATTACKPOWER = 191,
		ATTACKPOWERMODIFIER = 192,
		PADDING = 193,
		MAX = 194,
	}
	#endregion

	#region enum PLAYERFIELDS
	public enum PLAYERFIELDS
	{
		SELECTION = 194,
		DUEL_ARBITER = 196,
		GUILD_ID = 198,
		GUILD_RANK = 199,
		BYTES_1 = 200,
		BYTES_2 = 201,
		DUEL_TEAM = 202,
		GUILD_TIMESTAMP = 203,
		INV_SLOTS = 204,
		PACK_SLOTS = 250,
		BANK_SLOTS = 282,
		BANKBAG_SLOTS = 330,
		FARSIGHT = 342,
		XP = 344,
		NEXTLEVEL_XP = 345,
		SKILL_INFO = 346,
		QUEST_INFO = 730,
		TALENT_POINTS = 810,
		SKILL_POINTS = 811,
		TRACK_CREATURES = 812,
		TRACK_RESOURCES = 813,
		CHAT_FILTERS = 814,
		BLOCK_PERCENTAGE = 815,
		DODGE_PERCENTAGE = 816,
		PARRY_PERCENTAGE = 817,
		BASE_MANA = 818,
		EXPLORED_ZONES = 819,
		REST_STATE_EXPERIENCE = 851,
		MAX = 852,
		MAX_NOTCLIENT = 250,
	}
	#endregion

	#region enum GAMEOBJECTFIELDS
	public enum GAMEOBJECTFIELDS
	{
		DISPLAYID = 6,
		FLAGS = 7,
		ROTATION = 8,
		STATE = 12,
		TIMESTAMP = 13,
		POS_X = 14,
		POS_Y = 15,
		POS_Z = 16,
		FACING = 17,
		DYNAMIC_FLAGS = 18,
		FACTION = 19,
		MAX = 20,
	}
	#endregion

	#region enum DYNAMICOBJECTFIELDS
	public enum DYNAMICOBJECTFIELDS
	{
		CASTER = 6,
		BYTES = 8,
		SPELLID = 9,
		RADIUS = 10,
		POS_X = 11,
		POS_Y = 12,
		POS_Z = 13,
		FACING = 14,
		PADDING = 15,
		MAX = 16,
	}
	#endregion

	#region enum CORPSEFIELDS
	public enum CORPSEFIELDS
	{
		OWNER = 6,
		FACING = 8,
		POS_X = 9,
		POS_Y = 10,
		POS_Z = 11,
		DISPLAYID = 12,
		ITEM0 = 13,
		BYTES_1 = 32,
		BYTES_2 = 33,
		GUILD = 34,
		FLAGS = 35,
		MAX = 36
	}
	#endregion

	#region enum POWERTYPE
	public enum POWERTYPE : byte
	{
		MANA,
		RAGE,
		FOCUS,
		ENERGY,
	}
	#endregion

	#region enum RACE
	public enum RACE : byte
	{
		HUMAN = 1,
		ORC = 2,
		DWARF = 3,
		NIGHTELF = 4,
		UNDEAD = 5,
		TAUREN = 6,
		GNOME = 7,
		TROLL = 8,
		GOBLIN = 0,
		MAX = 9
	}
	#endregion

	#region enum CLASS
	public enum CLASS : byte
	{
		WARRIOR = 1,
		PALADIN = 2,
		HUNTER = 3,
		ROGUE = 4,
		PRIEST = 5,
		SHAMAN = 7,
		MAGE = 8,
		WARLOCK = 9,
		DRUID = 11,
	}
	#endregion

	#region enum GUILDRANK
	public enum GUILDRANK : int
	{
		GM,
		OFFICER,
		VETERAN,
		MEMBER,
		INITIATE
	}
	#endregion
}
